AWSTemplateFormatVersion: 2010-09-09
Description: Deploy EC2

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9
      InstanceType: t2.micro
      SubnetId: subnet-090e5cd4b6016dc76
      Tags:
        - Key: Name
          Value: vm
